modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="calemiutils"

version="1.15.2-1.1.2"

displayName="Calemi's Utils"

updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/calemis-utilities?gameCategorySlug=mc-mods&projectID=320196"

logoFile="logo.png"

credits="Kryto627 for helping with some code."

authors="Calemi"

description='''
Utilities that make your Minecraft experience better!
'''